
###
POST http://localhost:3000/auth/login3
content-type: application/json

{
  "password": "1234",
  "email": "aa@naver.com"
}

###
POST http://localhost:3000/auth/login3
content-type: application/json

{
  "password": "12345",
  "email": "leee@naver.com"
}

###
GET http://localhost:3000/auth/test-guard2
###가드 테스트
GET http://localhost:3000/auth/test-guard

###가드 로그인
POST http://localhost:3000/auth/login2
content-type: application/json

{
  "password": "1234",
  "email": "leeeee@naver.com"
}

### Create ❶ 유저 생성
POST http://localhost:3000/auth/login
content-type: application/json

{
  "username": "lee",
  "password": "1234",
  "email": "leeeee@naver.com"
}

### GetUser ❷ 유저 정보 찾기 
GET http://localhost:3000/user/getUser/anddd222y@podo.com


### Update User ❸ 유저 정보 업데이트 
PUT http://localhost:3000/user/update/andy@podo.com
content-type: application/json

{
  "email": "andy@podo.com",
  "username": "andy2",
  "password": "test12345"
}

### Delete User  ❹ 유저 삭제 
DELETE http://localhost:3000/user/delete/andy@podo.com

### 잘못된 이메일을 입력한 경우 
POST http://localhost:3000/auth/register
content-type: application/json

{
  "username": "lee",
  "password": "1234",
  "email": "aa@naver.com"
}
